[Interface]
Address = 10.0.0.1/24, 2a01:4f9:c010:91e9:f000::1/68
ListenPort = 51820
PrivateKey = WADoXT+eEQOj92x9lO6kAw2GoTSTAZGzI89ycmQMoWw=

# IPv4 needs NAT/Masquerade because 10.0.0.x is private.
# IPv6 traffic is routed through the 'wg-hub' tunnel to Hetzner.
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp6s18 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enp6s18 -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT

[Peer]
# Example Peer (will be populated by API)
PublicKey = zqdoJRS5e23u2vN3467nBoediHz8cZHj60/IdyPE9hc=
AllowedIPs = 10.0.0.2/32, 2a01:4f9:c010:91e9::2/128
